#!/bin/zsh
# oMLX Widget installer — sets up oMLX and the widget under ~/AI.
#
#   curl -fsSL https://raw.githubusercontent.com/ooberguts/oMLX-widget/main/install.sh | zsh
#
# Everything lives in one tree. Nothing goes into system Python, and Homebrew
# is not required or installed.
#
#   AI_ROOT=/somewhere/else   install elsewhere (default ~/AI)
#   OMLX_REF=v0.7.0.dev4      pin the oMLX version (default: latest tag)
#   WITH_KERNELS=0            skip the Metal kernel build
#   WIDGET_ONLY=1             only rebuild the widget
set -euo pipefail

AI_ROOT="${AI_ROOT:-$HOME/AI}"
WIDGET_REPO="https://github.com/ooberguts/oMLX-widget.git"
OMLX_REPO="https://github.com/jundot/omlx.git"
PORT="${OMLX_PORT:-8000}"

say()  { print -P "%F{cyan}==>%f $*"; }
warn() { print -P "%F{yellow}  !%f $*"; }
die()  { print -P "%F{red}  x%f $*"; exit 1; }

# ── preflight ────────────────────────────────────────────────────────────────
[[ "$(uname -s)" == "Darwin" ]] || die "macOS only"
[[ "$(uname -m)" == "arm64"  ]] || die "Apple Silicon only"
xcode-select -p >/dev/null 2>&1 || die "Command Line Tools missing — run: xcode-select --install"
command -v swiftc >/dev/null || die "swiftc missing — run: xcode-select --install"

RAM_GB=$(( $(sysctl -n hw.memsize) / 1073741824 ))
# Leave headroom for the OS; the guard is a ceiling, not a reservation.
GUARD_GB=$(( RAM_GB > 32 ? RAM_GB - 15 : RAM_GB / 2 ))
say "macOS on Apple Silicon, ${RAM_GB} GB — memory guard will be ${GUARD_GB} GB"

mkdir -p "$AI_ROOT"/{models,omlx/bin,omlx/data,cache/kv,logs,apps}

# ── widget ───────────────────────────────────────────────────────────────────
say "fetching the widget"
WSRC="$AI_ROOT/apps/OMLXWidget"
if [[ -d "$WSRC/.git" ]]; then
  git -C "$WSRC" pull --ff-only --quiet || warn "could not fast-forward the widget; leaving it alone"
else
  rm -rf "$WSRC"
  git clone --quiet "$WIDGET_REPO" "$WSRC"
fi

if [[ "${WIDGET_ONLY:-0}" == "1" ]]; then
  say "building the widget"
  OMLX_WIDGET_APP="$AI_ROOT/apps/oMLX Widget.app" "$WSRC/build.sh"
  say "done — open \"$AI_ROOT/apps/oMLX Widget.app\""
  exit 0
fi

# ── python, via uv (never the system interpreter) ────────────────────────────
if ! command -v uv >/dev/null && [[ ! -x "$HOME/.local/bin/uv" ]]; then
  say "installing uv"
  curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null
fi
export PATH="$HOME/.local/bin:$PATH"
uv python install 3.12 >/dev/null 2>&1 || true

# ── oMLX ─────────────────────────────────────────────────────────────────────
OSRC="$AI_ROOT/omlx/src"
if [[ -d "$OSRC/.git" ]]; then
  git -C "$OSRC" fetch --tags --quiet
else
  say "cloning oMLX"
  git clone --quiet "$OMLX_REPO" "$OSRC"
fi
REF="${OMLX_REF:-$(git -C "$OSRC" tag --sort=-v:refname | head -1)}"
say "checking out oMLX $REF"
git -C "$OSRC" checkout --quiet "$REF"

say "creating the virtualenv"
uv venv --python 3.12 "$AI_ROOT/omlx/.venv" >/dev/null

# Metal kernels are opt-in and need cmake+ninja; without them Bonsai and the
# Qwen prefill path fall back to slower generic code.
KERNEL_ENV=()
if [[ "${WITH_KERNELS:-1}" == "1" ]]; then
  say "installing cmake + ninja for the Metal kernels"
  VIRTUAL_ENV="$AI_ROOT/omlx/.venv" uv pip install --quiet cmake ninja || warn "cmake/ninja failed; skipping kernels"
  if VIRTUAL_ENV="$AI_ROOT/omlx/.venv" uv pip show cmake >/dev/null 2>&1; then
    KERNEL_ENV=(OMLX_WITH_CUSTOM_KERNEL=1)
    say "building oMLX with Metal kernels (this takes a few minutes)"
  fi
else
  say "installing oMLX without Metal kernels"
fi
env "${KERNEL_ENV[@]}" VIRTUAL_ENV="$AI_ROOT/omlx/.venv" \
  PATH="$AI_ROOT/omlx/.venv/bin:$PATH" \
  uv pip install --quiet -e "$OSRC" || die "oMLX install failed"

# ── control script ───────────────────────────────────────────────────────────
say "writing omlxctl"
cat > "$AI_ROOT/omlx/bin/omlxctl" <<CTL
#!/bin/zsh
# oMLX control script. Generated by install.sh — safe to edit.
set -u
AI_ROOT="$AI_ROOT"
OMLX="\$AI_ROOT/omlx/.venv/bin/omlx"
LABEL="ai.omlx.server"
PLIST="\$HOME/Library/LaunchAgents/\$LABEL.plist"
PORT="\${OMLX_PORT:-$PORT}"

case "\${1:-}" in
  start)   launchctl bootstrap "gui/\$UID" "\$PLIST" 2>/dev/null \\
             || launchctl kickstart -k "gui/\$UID/\$LABEL"; echo "starting oMLX on port \$PORT" ;;
  stop)    launchctl bootout "gui/\$UID/\$LABEL" 2>/dev/null \\
             || launchctl kill TERM "gui/\$UID/\$LABEL" 2>/dev/null; echo "stopped oMLX" ;;
  restart) "\$0" stop >/dev/null 2>&1; sleep 1; "\$0" start ;;
  status)  curl -sf --max-time 2 "http://127.0.0.1:\$PORT/v1/models" >/dev/null 2>&1 \\
             && echo running || echo stopped ;;
  serve)
    exec "\$OMLX" serve \\
      --base-path "\$AI_ROOT/omlx/data" \\
      --model-dir "\$AI_ROOT/models" \\
      --paged-ssd-cache-dir "\$AI_ROOT/cache/kv" \\
      --paged-ssd-cache-max-size 200GB \\
      --hot-cache-max-size 8GB --hot-cache-write-through \\
      --memory-guard-gb "\${OMLX_MEM_GB:-$GUARD_GB}" \\
      --max-concurrent-requests 1 \\
      --host 127.0.0.1 --port "\$PORT" --log-level info ;;
  *) echo "usage: omlxctl {start|stop|restart|status|serve}" >&2; exit 2 ;;
esac
CTL
chmod +x "$AI_ROOT/omlx/bin/omlxctl"

# ── launch agent ─────────────────────────────────────────────────────────────
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$HOME/Library/LaunchAgents/ai.omlx.server.plist" <<PL
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>ai.omlx.server</string>
  <key>ProgramArguments</key>
  <array><string>$AI_ROOT/omlx/bin/omlxctl</string><string>serve</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><false/>
  <key>StandardOutPath</key><string>$AI_ROOT/logs/omlx.out.log</string>
  <key>StandardErrorPath</key><string>$AI_ROOT/logs/omlx.err.log</string>
  <key>WorkingDirectory</key><string>$AI_ROOT</string>
  <key>ProcessType</key><string>Interactive</string>
</dict>
</plist>
PL

# ── widget build ─────────────────────────────────────────────────────────────
say "building the widget"
OMLX_WIDGET_APP="$AI_ROOT/apps/oMLX Widget.app" "$WSRC/build.sh"

# ── start and open the local admin API for the widget ────────────────────────
say "starting oMLX"
"$AI_ROOT/omlx/bin/omlxctl" start >/dev/null 2>&1 || true
for i in {1..30}; do
  [[ "$("$AI_ROOT/omlx/bin/omlxctl" status)" == "running" ]] && break
  sleep 1
done

# The widget reads /admin/api/*. Safe here only because oMLX binds to loopback.
SETTINGS="$AI_ROOT/omlx/data/settings.json"
if [[ -f "$SETTINGS" ]]; then
  /usr/bin/python3 - "$SETTINGS" <<'PYS' || true
import json, sys
p = sys.argv[1]
d = json.load(open(p))
d.setdefault("auth", {})["skip_api_key_verification"] = True
d.setdefault("idle_timeout", {})["idle_timeout_seconds"] = 900
json.dump(d, open(p, "w"), indent=2)
PYS
  "$AI_ROOT/omlx/bin/omlxctl" restart >/dev/null 2>&1 || true
fi

print
say "installed"
cat <<DONE

  root        $AI_ROOT
  models      $AI_ROOT/models
  server      http://127.0.0.1:$PORT   (omlxctl start|stop|status)
  widget      $AI_ROOT/apps/oMLX Widget.app

  open "$AI_ROOT/apps/oMLX Widget.app"

  Add ~/AI/omlx/bin to your PATH for omlxctl:
    echo 'export PATH="$AI_ROOT/omlx/bin:\$PATH"' >> ~/.zshrc

  No models yet — use the widget's Models tab to download one.
DONE
